spring.application.name=biblioteca
# Configuração do Banco H2
spring.datasource.url=jdbc:h2:mem:bibliotecadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (Para acessarmos o banco pelo navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console